spring.application.name=user-service


server.servlet.context-path=/userService
spring.data.mongodb.uri=mongodb+srv://akhilbabuk92:85ANz3vvRgUsTPOF@cluster-vet01.tffoee8.mongodb.net/vet-app?authSource=admin&authMechanism=SCRAM-SHA-1
